### ISSUE TITLE
Consider adding @property to variables

### ISSUE THREAD

**Issue by literat** [literat/litera#45]
```css
@property --pink {
  syntax: '<color>';
}
```

https://developer.mozilla.org/en-US/docs/Web/CSS/@property
